- name: Installa Docker e configura il registry
  hosts: all
  
  tasks:

    # container 1 
    - name: Avvio container 1 (Ubuntu)
      become: yes
      community.docker.docker_container:
        name: ubuntu
        image: giulia005/ubuntu:latest
        state: started 
        user: root 
        restart_policy: always
        privileged: true 
        ports: 
          - "7070:22"
        

    # container 2
    - name: Avvio container 2 (Rocky)
      become: yes
      community.docker.docker_container:
        name: rocky
        image: giulia005/rocky:latest
        state: started 
        user: root 
        restart_policy: always
        privileged: true 
        ports:
          - "7075:22"